/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as PostcaseIndexImport } from './routes/postcase.index'
import { Route as PostcaseEmrintakeImport } from './routes/postcase.emrintake'
import { Route as PostcaseAddfromemrIdentifierImport } from './routes/postcase.addfromemr.$identifier'
import { Route as PostcasePatientIdCaseIdImport } from './routes/postcase.$patientId.$caseId'

// Create/Update Routes

const AboutRoute = AboutImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PostcaseIndexRoute = PostcaseIndexImport.update({
  path: '/postcase/',
  getParentRoute: () => rootRoute,
} as any)

const PostcaseEmrintakeRoute = PostcaseEmrintakeImport.update({
  path: '/postcase/emrintake',
  getParentRoute: () => rootRoute,
} as any)

const PostcaseAddfromemrIdentifierRoute =
  PostcaseAddfromemrIdentifierImport.update({
    path: '/postcase/addfromemr/$identifier',
    getParentRoute: () => rootRoute,
  } as any)

const PostcasePatientIdCaseIdRoute = PostcasePatientIdCaseIdImport.update({
  path: '/postcase/$patientId/$caseId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/postcase/emrintake': {
      id: '/postcase/emrintake'
      path: '/postcase/emrintake'
      fullPath: '/postcase/emrintake'
      preLoaderRoute: typeof PostcaseEmrintakeImport
      parentRoute: typeof rootRoute
    }
    '/postcase/': {
      id: '/postcase/'
      path: '/postcase'
      fullPath: '/postcase'
      preLoaderRoute: typeof PostcaseIndexImport
      parentRoute: typeof rootRoute
    }
    '/postcase/$patientId/$caseId': {
      id: '/postcase/$patientId/$caseId'
      path: '/postcase/$patientId/$caseId'
      fullPath: '/postcase/$patientId/$caseId'
      preLoaderRoute: typeof PostcasePatientIdCaseIdImport
      parentRoute: typeof rootRoute
    }
    '/postcase/addfromemr/$identifier': {
      id: '/postcase/addfromemr/$identifier'
      path: '/postcase/addfromemr/$identifier'
      fullPath: '/postcase/addfromemr/$identifier'
      preLoaderRoute: typeof PostcaseAddfromemrIdentifierImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/postcase/emrintake': typeof PostcaseEmrintakeRoute
  '/postcase': typeof PostcaseIndexRoute
  '/postcase/$patientId/$caseId': typeof PostcasePatientIdCaseIdRoute
  '/postcase/addfromemr/$identifier': typeof PostcaseAddfromemrIdentifierRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/postcase/emrintake': typeof PostcaseEmrintakeRoute
  '/postcase': typeof PostcaseIndexRoute
  '/postcase/$patientId/$caseId': typeof PostcasePatientIdCaseIdRoute
  '/postcase/addfromemr/$identifier': typeof PostcaseAddfromemrIdentifierRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/postcase/emrintake': typeof PostcaseEmrintakeRoute
  '/postcase/': typeof PostcaseIndexRoute
  '/postcase/$patientId/$caseId': typeof PostcasePatientIdCaseIdRoute
  '/postcase/addfromemr/$identifier': typeof PostcaseAddfromemrIdentifierRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/postcase/emrintake'
    | '/postcase'
    | '/postcase/$patientId/$caseId'
    | '/postcase/addfromemr/$identifier'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/postcase/emrintake'
    | '/postcase'
    | '/postcase/$patientId/$caseId'
    | '/postcase/addfromemr/$identifier'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/postcase/emrintake'
    | '/postcase/'
    | '/postcase/$patientId/$caseId'
    | '/postcase/addfromemr/$identifier'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  PostcaseEmrintakeRoute: typeof PostcaseEmrintakeRoute
  PostcaseIndexRoute: typeof PostcaseIndexRoute
  PostcasePatientIdCaseIdRoute: typeof PostcasePatientIdCaseIdRoute
  PostcaseAddfromemrIdentifierRoute: typeof PostcaseAddfromemrIdentifierRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  PostcaseEmrintakeRoute: PostcaseEmrintakeRoute,
  PostcaseIndexRoute: PostcaseIndexRoute,
  PostcasePatientIdCaseIdRoute: PostcasePatientIdCaseIdRoute,
  PostcaseAddfromemrIdentifierRoute: PostcaseAddfromemrIdentifierRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/postcase/emrintake",
        "/postcase/",
        "/postcase/$patientId/$caseId",
        "/postcase/addfromemr/$identifier"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/postcase/emrintake": {
      "filePath": "postcase.emrintake.tsx"
    },
    "/postcase/": {
      "filePath": "postcase.index.tsx"
    },
    "/postcase/$patientId/$caseId": {
      "filePath": "postcase.$patientId.$caseId.tsx"
    },
    "/postcase/addfromemr/$identifier": {
      "filePath": "postcase.addfromemr.$identifier.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
