/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as PostcaseIndexImport } from './routes/postcase.index'
import { Route as PostcaseEmrImport } from './routes/postcase.emr'
import { Route as PostcasePatientIdCaseIdImport } from './routes/postcase.$patientId.$caseId'

// Create/Update Routes

const AboutRoute = AboutImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PostcaseIndexRoute = PostcaseIndexImport.update({
  path: '/postcase/',
  getParentRoute: () => rootRoute,
} as any)

const PostcaseEmrRoute = PostcaseEmrImport.update({
  path: '/postcase/emr',
  getParentRoute: () => rootRoute,
} as any)

const PostcasePatientIdCaseIdRoute = PostcasePatientIdCaseIdImport.update({
  path: '/postcase/$patientId/$caseId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/postcase/emr': {
      id: '/postcase/emr'
      path: '/postcase/emr'
      fullPath: '/postcase/emr'
      preLoaderRoute: typeof PostcaseEmrImport
      parentRoute: typeof rootRoute
    }
    '/postcase/': {
      id: '/postcase/'
      path: '/postcase'
      fullPath: '/postcase'
      preLoaderRoute: typeof PostcaseIndexImport
      parentRoute: typeof rootRoute
    }
    '/postcase/$patientId/$caseId': {
      id: '/postcase/$patientId/$caseId'
      path: '/postcase/$patientId/$caseId'
      fullPath: '/postcase/$patientId/$caseId'
      preLoaderRoute: typeof PostcasePatientIdCaseIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/postcase/emr': typeof PostcaseEmrRoute
  '/postcase': typeof PostcaseIndexRoute
  '/postcase/$patientId/$caseId': typeof PostcasePatientIdCaseIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/postcase/emr': typeof PostcaseEmrRoute
  '/postcase': typeof PostcaseIndexRoute
  '/postcase/$patientId/$caseId': typeof PostcasePatientIdCaseIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/postcase/emr': typeof PostcaseEmrRoute
  '/postcase/': typeof PostcaseIndexRoute
  '/postcase/$patientId/$caseId': typeof PostcasePatientIdCaseIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/postcase/emr'
    | '/postcase'
    | '/postcase/$patientId/$caseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/postcase/emr'
    | '/postcase'
    | '/postcase/$patientId/$caseId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/postcase/emr'
    | '/postcase/'
    | '/postcase/$patientId/$caseId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  PostcaseEmrRoute: typeof PostcaseEmrRoute
  PostcaseIndexRoute: typeof PostcaseIndexRoute
  PostcasePatientIdCaseIdRoute: typeof PostcasePatientIdCaseIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  PostcaseEmrRoute: PostcaseEmrRoute,
  PostcaseIndexRoute: PostcaseIndexRoute,
  PostcasePatientIdCaseIdRoute: PostcasePatientIdCaseIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/postcase/emr",
        "/postcase/",
        "/postcase/$patientId/$caseId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/postcase/emr": {
      "filePath": "postcase.emr.tsx"
    },
    "/postcase/": {
      "filePath": "postcase.index.tsx"
    },
    "/postcase/$patientId/$caseId": {
      "filePath": "postcase.$patientId.$caseId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
